name: Gatsby Publish

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
      - name: get time
        id: get-time
        run: |
          echo "::set-output name=time::$(/bin/date -u +%Y%m%d%m%s)"
        shell: bash
      - uses: actions/cache@v2.1.6
        with: 
          path: |
            node_modules/
            .cache/
          key: ${{ runner.os }}-${{ steps.get-time.outputs.time }}
